name: Neo4j GraphQL Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:4.4.42-enterprise
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
          NEO4J_AUTH: neo4j/password
          NEO4J_dbms_memory_heap_initial__size: 512m
          NEO4J_dbms_memory_heap_max__size: 1G
          NEO4J_dbms_memory_pagecache_size: 512m
          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7474:7474
          - 7687:7687
        options: >-
          --health-cmd "cypher-shell -u neo4j -p password 'RETURN 1;'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Neo4j to be ready
        run: |
          # Simple delay to ensure Neo4j is fully initialized
          sleep 10
          echo "Neo4j should be ready"

      - name: Run tests
        run: npm test
        env:
          NEO4J_URI: bolt://localhost:7687
          NEO4J_USER: neo4j
          NEO4J_PASSWORD: password 